### ISSUE TITLE
`Could not compile teal without compatibility library` in `embed_compiler!`

### ISSUE THREAD

**Issue by makspll** [lenscas/tealr#47]
Currently if lua is not installed I am getting the error:
```
Could not compile teal without compatibility library
```
This is not realy obvious to the end-user, especially if the user is not aware of tealr being a dependency.

Something like:
```
Could not find lua on your system, tealr requires lua to be available at compile time to embed the compiler.
```
would be more descriptive.

**Comment by makspll** [comment]
Also, I just tried this example: 

```rust
use tealr::{embed_compiler};


fn main() -> std::io::Result<()> {
  
    let a = embed_compiler!("v0.9.0");

    Ok(())
}
```
with lua installed on my machine:
```shell
>$ lua
Lua 5.3.3  Copyright (C) 1994-2016 Lua.org, PUC-Rio
> 
```
and ended up getting the same error.

**Comment by makspll** [comment]
I notice this error in the debugger:

```shell
warning: 1 warning emitted

lua: tl:122: module 'argparse' not found:
	no field package.preload['argparse']
	no file './argparse.lua'
	no file '/usr/local/share/lua/5.3/argparse.lua'
	no file '/usr/local/share/lua/5.3/argparse/init.lua'
	no file '/usr/local/lib/lua/5.3/argparse.lua'
	no file '/usr/local/lib/lua/5.3/argparse/init.lua'
	no file '/usr/share/lua/5.3/argparse.lua'
	no file '/usr/share/lua/5.3/argparse/init.lua'
	no file './argparse.lua'
	no file './argparse/init.lua'
	no file '/usr/local/lib/lua/5.3/argparse.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.3/argparse.so'
	no file '/usr/lib/lua/5.3/argparse.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './argparse.so'
stack traceback:
	[C]: in function 'require'
	tl:122: in main chunk
	[C]: in ?
```

**Comment by lenscas** [comment]
Actually, `lua` is not a dependency for the `embed_compiler!` macro. The teal compiler is, which has standalone versions available. 

I can't fall back to loading the teal compiler source that it downloaded as that has its own dependencies when it needs to be invoked through the CLI.

**Comment by makspll** [comment]
I was going off of "This needs to be able to run `lua` at compile time to compile the teal compiler" which seems to suggest the opposite! 

If this macro requires tl to be installed could you explain what the point of the macro is in this case? 

I am trying to port over from rlua to this library now but aren't very familiar with the teal project!

**Comment by lenscas** [comment]
> I was going off of "This needs to be able to run lua at compile time to compile the teal compiler" which seems to suggest the opposite!

When I wrote this macro there where no stand alone versions of teal available, so back then this was correct though indeed not the most clear. Right now, this documentation is indeed not correct anymore and I should've fixed it, sadly it slipped my mind.

> If this macro requires tl to be installed could you explain what the point of the macro is in this case?

Teal scripts can run directly in the lua VM after the teal compiler got loaded into it. This macro helps setting that up by
1: Compiling the teal compiler so it doesn't depend on the compatibility library (Which is a C library)
2: embedding this version in your code 
3: creating a new function that uses the embedded compiler that sets all this patchwork up for you

> I am trying to port over from rlua to this library now but aren't very familiar with the teal project!

You don't have to interact with teal if you want to use this library. Nor do you need this macro if you don't want to. The original goal of tealr was to help make it easier to work with teal, which is why there are so many references to it when it comes to the names of, well, almost everything.

However, you can use the documentation features without having to think about the teal project. Just make sure everything you want to share implements `TypeName` and `TypeBody`, use the [TypeWalker](https://docs.rs/tealr/latest/tealr/struct.TypeWalker.html) to process every type and serialize it to json. Then use `tealr_doc_gen` to create the online docs based on the json file.

**Comment by makspll** [comment]
> When I wrote this macro there where no stand alone versions of teal available, so back then this was correct though indeed not the most clear. Right now, this documentation is indeed not correct anymore and I should've fixed it, sadly it slipped my mind.

> Teal scripts can run directly in the lua VM after the teal compiler got loaded into it. This macro helps setting that up by
> 1: Compiling the teal compiler so it doesn't depend on the compatibility library (Which is a C library)
> 2: embedding this version in your code
> 3: creating a new function that uses the embedded compiler that sets all this patchwork up for you

Ah that makes a lot of sense, thanks for the explanation! Is it possible to instead of running teal at runtime, just verify a teal program once (I guess missing out on runtime teal errors) and yet still execute it as lua? 

> You don't have to interact with teal if you want to use this library. Nor do you need this macro if you don't want to. The original goal of tealr was to help make it easier to work with teal, which is why there are so many references to it when it comes to the names of, well, almost everything.


Yep I am aware of this, I just think enabling full teal integration in my project would be neat as well!

**Comment by lenscas** [comment]
> Ah that makes a lot of sense, thanks for the explanation! Is it possible to instead of running teal at runtime, just verify a teal program once (I guess missing out on runtime teal errors) and yet still execute it as lua?

teal scripts can be compiled ahead of time to lua as well. Also, teal shouldn't add any runtime checks. So, compiling ahead of time shouldn't make you miss out on errors (In fact, the opposite is true as when loading teal scripts directly in the lua VM instead of doing AOT it favors performance at the cost of checks.) 

> Yep I am aware of this, I just think enabling full teal integration in my project would be neat as well!

Teal likes to assume that the "compat" library either exists or the compiler is running in lua5.3 or 5.4. So, I am not sure if it will run in luajit without this C library and if it does, for how long it will work. Running teal scripts this way also increases the load time of scripts, which may not be desirable.

I think a better way would be to generate the `.d.tl` file (Which you need anyway) and just have users compile the scripts ahead of time. That would also save on having to ship the teal compiler as part of the final binary.

I can expose a parameter to the macro so it doesn't exclude this compat library though, but you would have to use https://docs.rs/mlua/latest/mlua/struct.Lua.html#method.unsafe_new function to create the lua instance to load it. I am also not sure if I can bundle this C library with the rest of the program.

So, if this is desired then it is probably best put behind a feature flag meant to allow more rapid prototyping while using teal during development, while compiling it to proper lua scripts for release builds.

**Comment by makspll** [comment]
> I think a better way would be to generate the .d.tl file (Which you need anyway) and just have users compile the scripts ahead of time. That would also save on having to ship the teal compiler as part of the final binary.

This was the original plan, But if you think there'd be problems with LuaJit then I should probably stick to it in that case!

**Comment by lenscas** [comment]
Keep in mind that people who really want to load `.tl` files directly can also just grab a compiled teal compiler and load it into the lua VM themselves, and this way they can also decide what version of teal to use.

**Comment by makspll** [comment]
True that's very convenient, that only works for external dependencies though right ? You can't use tile in the same file that loads it right ?

**Comment by lenscas** [comment]
no, but you can make a simple lua file that just does
```lua
local tl = require "tl"
tl.loader()
require "fileYouActuallyWantToLoad"
```
